sudo: required
services: 
  - docker

before_install:
  - docker build -t dan78/docker-react-1 -f Dockerfile.dev .

script:
  - docker run dan78/docker-react-1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET-KEY"

